### ISSUE TITLE
Request for Update: Flutter 3.29.0 and Android API Support

### ISSUE THREAD

**Issue by Whitecloude** [Instabug/Instabug-Flutter#552]
Hi there,

After upgrading to Flutter 3.29.0, I noticed that some APIs are no longer supported on Android. It appears that your library is affected by these changes. Could you please update the library to be compatible with the new version?

I found the following article, which might provide some useful insights:
https://benamorn.medium.com/today-i-learned-after-upgrading-to-flutter-3-29-0-7c7ab1a97975

Thank you for your attention to this matter!

**Comment by favazHF** [comment]
Same case here, the app doesn't compile on flutter 3.29.0 because of the Instabug library.

```
/Users/xxxx/.pub-cache/hosted/pub.dev/instabug_flutter-14.1.0/android/src/main/java/com/instabug/flutter/InstabugFlutterPlugin.java:42: error: cannot find symbol
    public static void registerWith(Registrar registrar) {
                                    ^
  symbol:   class Registrar
  location: class InstabugFlutterPlugin
```

**Comment by MaciejCaputa** [comment]
I also encountered the same issue

**Comment by MaciejCaputa** [comment]
Hi, do you have any plans for resolving the issue?

**Comment by bsz0206** [comment]
The build fails on 3.29.1

Flutter 3.29.1 • channel [user-branch] • unknown source
Framework • revision 09de023485 (9 days ago) • 2025-02-28 13:44:05 -0800
Engine • revision 871f65ac1b
Tools • Dart 3.7.0 • DevTools 2.42.2

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\behra\AppData\Local\Pub\Cache\hosted\pub.dev\instabug_flutter-14.1.0\android\src\main\java\com\instabug\flutter\InstabugFlutterPlugin.java:30: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
C:\Users\behra\AppData\Local\Pub\Cache\hosted\pub.dev\instabug_flutter-14.1.0\android\src\main\java\com\instabug\flutter\InstabugFlutterPlugin.java:42: error: cannot find symbol
    public static void registerWith(Registrar registrar) {
                                    ^
  symbol:   class Registrar
  location: class InstabugFlutterPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instabug_flutter:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler output below.
  Note: Recompile with -Xlint:deprecation for details.Note: Recompile with -Xlint:unchecked for details.C:\Users\behra\AppData\Local\Pub\Cache\hosted\pub.dev\instabug_flutter-14.1.0\android\src\main\java\com\instabug\flutter\InstabugFlutterPlugin.java:30: error: cannot find symbol
  import io.flutter.plugin.common.PluginRegistry.Registrar;
                                                ^
    symbol:   class Registrar
    location: interface PluginRegistry
  C:\Users\behra\AppData\Local\Pub\Cache\hosted\pub.dev\instabug_flutter-14.1.0\android\src\main\java\com\instabug\flutter\InstabugFlutterPlugin.java:42: error: cannot find symbol
      public static void registerWith(Registrar registrar) {
                                      ^
    symbol:   class Registrar
    location: class InstabugFlutterPluginNote: Some input files use unchecked or unsafe operations.Note: Some input files use or override a deprecated API.
  2 errors

* Try:
> Check your code and dependencies to fix the compilation error(s)
> Run with --scan to get full insights.

BUILD FAILED in 1m 22s
Running Gradle task 'assembleRelease'...                           82.9s
Gradle task assembleRelease failed with exit code 1

**Comment by arigilder** [comment]
I'm also seeing the same error.

**Comment by bsz0206** [comment]
We need someone from instabug to take care of this.

**Comment by MoKamall** [comment]
We are currently aware of this and working on it. Apologies for any inconvenience caused!

**Comment by hyeongminjeon** [comment]
Any update?

**Comment by Sahad2701** [comment]
This issue happens due to the old Flutter v1 embedding. A temporary fix has been pushed here:  
https://github.com/Instabug/Instabug-Flutter/pull/558/commits/b6b761059288beef7121d6b3d043f90702ecc342

Until the package is officially updated, you can use that commit directly:

```yaml
instabug_flutter:
  git:
    url: https://github.com/Instabug/Instabug-Flutter.git
    ref: b6b761059288beef7121d6b3d043f90702ecc342
```

Should help build the flutter app for now.

**Comment by bsz0206** [comment]
Still issues:
../../AppData/Local/Pub/Cache/git/Instabug-Flutter-b6b761059288beef7121d6b3d043f90702ecc342/lib/src/utils/feature_flags_manager.dart:30:20: Error: 'InstabugHostApi' isn't a type.
  void $setHostApi(InstabugHostApi host) {


> This issue happens due to the old Flutter v1 embedding. A temporary fix has been pushed here: [b6b7610](https://github.com/Instabug/Instabug-Flutter/commit/b6b761059288beef7121d6b3d043f90702ecc342)
> 
> Until the package is officially updated, you can use that commit directly:
> 
> instabug_flutter:
>   git:
>     url: https://github.com/Instabug/Instabug-Flutter.git
>     ref: b6b761059288beef7121d6b3d043f90702ecc342
> Should help build the flutter app for now.

**Comment by NaarGes** [comment]
I'm facing same issue. any updates?

**Comment by ConorEdwardsCP** [comment]
Our team is also experiencing the same issue. We had to create two different branches for our app, one using Flutter 3.29.2 to support iOS 18, and one with flutter 3.27.4 to support Android, since this is not currently fixed. Any progress that can get made on this to make it capable of working with the latest Flutter version would be very much appreciated.

**Comment by bsz0206** [comment]
@MoKamall  does the company have any plan to fix this? this should be an easy one.

**Comment by awaisjamil-mp** [comment]
its been more than a month since flutter update and we are stuck due to this issue. any plan to resolve it soon????

**Comment by MoKamall** [comment]
Hey all, a fix for this will be out with our next release (which will be due very soon). Please keep an eye out for it!

**Comment by bsz0206** [comment]
@MoKamall can you let us know how many days is very soon?

**Comment by MoKamall** [comment]
The new release `v14.3.0` is now out! It officialy includes a fix for this issue. 

We apologize for any invonveniences or delays. Thank you for understanding!
